runtime: nodejs18
build_env_variables:
  DB_TYPE: postgres
  DB_HOST: 'localhost'
  DB_PORT: 5432
  DB_USERNAME: 'postgres'
  DB_PASSWORD: 'umcms'
  DB_NAME: 'umcms'

  #JWT Secret
  JWT_SECRET: secret